### ISSUE TITLE
As CORE-ENGINE, There needs to be a way to execute permissibility rules CG0014, CG0015, CG0016, CG0431, CG0651

### ISSUE THREAD

**Issue by nhaydel** [cdisc-org/cdisc-rules-engine#112]
With this impediment resolution, CG0014 and CG0016 should be able to be fully executed.
CG0015, CG0431, and CG0651 will need Define.xml functionality as well in order to be partially executable (separate Impediment).

To execute these rules, we need to perform a permissibility check against all variables in all datasets (not just specified variables).  The permissibility should still come from the CDISC library.

![rule_table](https://user-images.githubusercontent.com/11080022/189713910-ded5ab06-96a5-4883-958a-74f88376a5b9.png)

**Comment by nhaydel** [comment]
@gcampion-cdisc  why does this need a new rule type?

**Comment by gcampion-cdisc** [comment]
@nhaydel We need a new rule type because of the scenarios where we are checking for Required or Expected variables. If a variable is Req or Exp in library, but missing in the data, we want to be able to flag this. In order to flag this, we need to iterate through the library variables, not the dataset variables. If we iterated through the dataset variables, when a required variable doesn't exist, it won't be iterated on and won't get flagged.

**Comment by nhaydel** [comment]
@gcampion-cdisc wouldn't this be better handled with an operation to get a list of required and expected variables and check if they are in the dataset?

**Comment by nhaydel** [comment]
I imagine the check looks something like this:
1. Operation to get list of all variables depending on permissibility
2. is_subset operator to check whether the variables are a a subset of the variables in the dataset.

Does that make sense?

Also what is the expected outcome of this issue? Based on the description, this issue does not result in authors being able to write these rules

**Comment by gcampion-cdisc** [comment]
I think the biggest difference is that your suggested approach would flag one issue for each dataset with missing variables, whereas, if we add a new rule type, we could flag an issue for each missing variable.

I think it would be preferable to flag an issue for each missing variable.

Keep in mind, for CG0014, there is more than one piece to the rule logic:
> Rule ID: CG0014
> Condition: Variable Core Status = Required
> Rule: Variable present in dataset and ^= null

I think the rule logic might get messy if we are checking if a set of library variables is a subset of variables in the dataset vs checking each library variable associated with the domain.

As a result of this issue, I expect CG0014 and CG0016 to be fully writable.

**Comment by nhaydel** [comment]
@gcampion-cdisc  Ok, now I think I understand the issue I am having with this rule. This rule can have two approaches:
1. The rule requires the engine examines each record be examined for missing data, but the report should be per variable.
    * with this approach, the engine would need to new rule type to get all variables applicable to the dataset with associated metadata. For example the rule type could be Library Variable Metadata Check.
    * This would produce the following dataset (additional columns can be added as more metadata is necessary:
    | Variable Name | Core | Label | 
    | ----------- | ----------- | ----------- |
    | STUDYID      | Req       | STUDYID |
    | USUBJID   | Req       | USUBJID |
    * Then an operation would be used to detect within the dataset whether the variable has missing values. Resulting in the following table:
    | Variable Name | Core | Label | Missing |
    | ----------- | ----------- | ----------- |
    | STUDYID      | Req       | STUDYID | True |
    | USUBJID   | Req       | USUBJID |  False |
2. Or you could report per record for the missing values that should be there.
So for each record the operation would return a list of values like [STUDYID, ...] if the values violate the permissibility for that variable. 

Do you have a preferred approach, or an approach which would be more applicable to all permissibility checks?

**Comment by gcampion-cdisc** [comment]
1. is good because it can be more generic and works with both Req and Exp.
2. is good because it will help the end user identify exactly which record violates the req permissibility, but it is bad because it will report for each record that doesn't contain the variable at all.

I think I prefer 1, but this might be a question for the bigger team.

**Comment by nhaydel** [comment]
Solution:

3. Split required permissibility check into two rules.
	* Required variables exist in dataset

      * Required variable is not empty - iterate over records
    | USUBJID | STUDYID  | Required Variables  | ...
    | -----   | -----    | ------                                 |
    | 001     | AAAA     |[A, B, C]                                      |
    | 002     | ""       |[A, B, C]                            |
    | ""      | ""       |[A, B, C]                      |

check:
  USUBJID is empty
  and USUBJID is_contained_by $required_variables

This requires 3 new operations: get_permissible_variables, get_required_variables, get_expected_variables
