### ISSUE TITLE
As a vendor implementing CORE, I want an OAS CORE API specification so that I can evaluate the CORE API against my own SDTM factory software to determine what data I need to implement CORE for conformance checking

### ISSUE THREAD

**Issue by nickdedonder** [cdisc-org/cdisc-rules-engine#143]
For the vendor outreach, we've had some requests for the API documentation, so we need it to help these vendors learn and evaluate the CORE API. We'd like to use OAS (Swagger) to document the API specification (similar to the Library and DDF)

**Comment by nhaydel** [comment]
Assuming this is referring to the App API and not the engine api. Also where should the swagger be stored?
