### ISSUE TITLE
Command to query a list of all the rules in a rule set

### ISSUE THREAD

**Issue by jamesformedix** [cdisc-org/cdisc-rules-engine#191]
We need a command to pull a list of all the rules for a given rule set from the cache, so that we can then allow the user to specify which ones they need and then pass them through to the validate command under the -r flag.

**Comment by nhaydel** [comment]
Does this issue already cover this functionality: https://github.com/cdisc-org/cdisc-rules-engine/issues/187 there is also an open PR for this issue

**Comment by jamesformedix** [comment]
Yes that already covers it thanks
