### ISSUE TITLE
Flag to specify .xpt files in the dataset folder to include/exclude from validation

### ISSUE THREAD

**Issue by jamesformedix** [cdisc-org/cdisc-rules-engine#193]
We want our application to let the user select a subset of datasets from their export folder if they want. The only way to do that currently is create a separate folder with the subset to then send to CORE CLI. It would be nice if we could do the validation without having to copy the dataset files over to this separate folder.

**Comment by alexfurmenkov** [comment]
@jamesformedix since we are now allowing absolute paths (https://github.com/cdisc-org/cdisc-rules-engine/pull/202), I think it makes sense to provide a new input parameter like `--dataset_path -dp` which can be multiple (`core validate ... -dp path_1 -dp path_2`)
