### ISSUE TITLE
Verbose progress output option parameter

### ISSUE THREAD

**Issue by jamesformedix** [cdisc-org/cdisc-rules-engine#199]
Currently the progress bar that is displayed on stdout during validation will tell the user what percentage of rules has been covered during validation. We would like another option parameter that instead of displaying a progress bar during validation, simply prints the current rule being validated against under a new line in the terminal. This should be more easily parseable by our application to understand how far the validation is, and will also provide more information to the user to let them know which specific rule is currently being validated against.

**Comment by nhaydel** [comment]
@jamesformedix Rules are executed in parallel. Would it be better to print rules as they are completed? Or maybe a start and end time for rule completion?

**Comment by jamesformedix** [comment]
> @jamesformedix Rules are executed in parallel. Would it be better to print rules as they are completed? Or maybe a start and end time for rule completion?

In that case I'd rather the engine simply prints rules as they are completed
