### ISSUE TITLE
Logs are enabled even without -vo and -l flag

### ISSUE THREAD

**Issue by jamesformedix** [cdisc-org/cdisc-rules-engine#214]
The engine still seems to be printing INFO level logs to stdout even when I run it without the -vo or -l flags. Here is the validate command I'm using:
`./core validate -s sdtmig -v 3-4 -d <PATH> -of JSON -of XLSX --disable-progressbar -rt <PATH>`

**Comment by jamesformedix** [comment]
I've also noticed that setting the -l to a high value still seems to print out INFO level logs. For instance this command still prints INFO logs to stdout for me:
`./core validate -s sdtmig -v 3-4 -d <PATH> -of JSON -of XLSX --disable-progressbar -rt <PATH> -l critical`

**Comment by nhaydel** [comment]
PR: https://github.com/cdisc-org/cdisc-rules-engine/pull/216
