### ISSUE TITLE
-l flag only for rule completion

### ISSUE THREAD

**Issue by jamesformedix** [cdisc-org/cdisc-rules-engine#215]
Would it be possible to add a new log flag to only print out which rules have been completed? I understand that if the -vo flag is included in the validate command then completed rules are signaled in stdout under the "Level 100" logs but I'm unaware right now of a way to only print these as no -l value exists in the README which corresponds to Level 100. 

The validation is currently being slowed down significantly for me by the added time the many INFO logs are taking to print to stdout and the only output I'm really interested in is knowing when rules have been completely validated.

**Comment by nhaydel** [comment]
if you don't specify the -l flag at all and only specify the -vo flag only the rule completion logs should appear @jamesformedix

**Comment by nhaydel** [comment]
For example when I run `python core.py validate -s sdtmig -v 3-4 -d /mnt/c/Users/NicHaydel/workspace/cdisc-rules-engine/XPT --disable-progressbar -vo` I only see rule completion logs. I will test with the executable now

**Comment by nhaydel** [comment]
@jamesformedix @alexfurmenkov I have noticed that this is only an issue on windows. I will have a patch PR up shortly

**Comment by nhaydel** [comment]
PR: https://github.com/cdisc-org/cdisc-rules-engine/pull/216
