### ISSUE TITLE
Improvement Request, result of list-rules valid JSON

### ISSUE THREAD

**Issue by JozefAerts** [cdisc-org/cdisc-rules-engine#218]
When one runs with "list-rules", a structure that looks like JSON, but isn't valid JSON as it starts with a "[" is returned.
I propose to make this valid JSON, e.g. by adding 
{ "rules": 
at the top (and also closing properly of course).
This would enable tools that load a set of rules (maybe for a specific standard) to easily parse the JSON and present a "rule selector" to the user, who can then decide wich rules to run against. For example:

![grafik](https://user-images.githubusercontent.com/25853332/204130606-5f22ac3e-fe01-46b7-b2d7-3c108cb9cbc0.png)

**Comment by nhaydel** [comment]
Arrays are valid json.

**Comment by JozefAerts** [comment]
Thanks! I will check again - it may be that this has been fixed in the mean time. 
Or that the tool that I use has it wrong ...

**Comment by nickdedonder** [comment]
Old issue that might have been fixed or is no longer an issue
