### ISSUE TITLE
CROG rule schema harmonization

### ISSUE THREAD

**Issue by gcampion-cdisc** [cdisc-org/cdisc-rules-engine#224]
This is a list of CROG rule schema harmonization updates that will need to be accounted for in the rules engine:

`Scopes.Classes.Include`
`Scopes.Classes.Exclude`
Use standard terminology (https://library.cdisc.org/browser/#/mdr/ct/2022-09-30/packages/define-xmlct-2022-09-30/codelists/C103329). For the current classes, this just means they will need to be converted to all-caps.

`Match Datasets.Name`
`Operations.domain`
`Scopes.Datasets.Include`
`Scopes.Datasets.Exclude`
`Scopes.Domains.Include`
`Scopes.Domains.Exclude`
Change "All" keyword to "ALL"

`Authority`
Convert value from object to list of objects, `Authorities`

`Scopes.Standards`
Move to be a property of `Authorities` items

`References`
Move to be a property of `Authorities.Standards` items

`Citations`
Move to be a property of `Authorities.Standards.References` items

`Scopes`
Rename to `Scope`

`Rule Types`
Replace the following Rule Types with new Rule Type `Record Data`:
- `Consistency`
- `Data Domain Aggregation`
- `Data Pattern and Format`
- `Date Arithmetic`
- `External Dictionaries`
- `Functional Dependency`
- `Populated Values`
- `Range & Limit`
- `Relationship Integrity Check`
- `Uniqueness`
- `Value Presence`
- `Variable Length`
- `Variable Order`
- `Variable Presence`

`Severity`
`Severity` is removed from the root and is now an optional property under `Authorities.Standards.References` for some authorities, like PMDA. For all rules, `Executability` should probably be reported instead - see below.

`Executability`
Added with following options:
- `Fully Executable`
- `Partially Executable - Possible Overreporting`
- `Partially Executable - Possible Underreporting`

`Core.Status`
Note that this will replace the rule metadata root-level `isPublished` property.
Added with following options:
- `Draft`
- `Published`

`Core.Id`
core id pattern is changing

- from: `CDISC.<STANDARD NAME>.<ORIGINAL ID>` aka `CDISC.SDTMIG.CG0001`
- to: a universal id like `CORE-000001`

**Comment by nhaydel** [comment]
@gcampion-cdisc removing severity is a big change because it affects  the excel output. What is severity replaced with?

**Comment by gcampion-cdisc** [comment]
@nhaydel I updated the details for severity for clarification.

I will get us a deadline for these changes. Let us know level of effort.

**Comment by nhaydel** [comment]
@gcampion-cdisc the code changes are pretty small, but I'd say it's a medium effort due to testing. I estimate it would take about a week to complete. 

We should probably also coordinate rollout of the schema change with a library and rule test endpoint update

**Comment by nhaydel** [comment]
Per Nick De Donder, we still want to report severity. If it is not provided the column will be empty

**Comment by gcampion-cdisc** [comment]
Added details about change to `Core.Id`

**Comment by gcampion-cdisc** [comment]
@nhaydel , I added a note for `Core.Status` in the issue details:
> Note that this will replace the rule metadata root-level `isPublished` property.
Mentioning because this will probably have an impact on the library loading logic.

**Comment by gcampion-cdisc** [comment]
@nhaydel, I had a discussion with the CROG team and asked if we can change "Authority" to "Authorities" for consistency with the rest of the schema, since it is a list. CROG agreed and I've updated the issue description here.

I'm making the change in the transformer, rule editor, and api and I think this should be a small change in the engine.

**Comment by nhaydel** [comment]
@gcampion-cdisc fortunately I had already used Authorities in the engine updates. So we should be good to go
