### ISSUE TITLE
Rule blocked: CORERULES-4, CORERULES-48, CORERULES-49

### ISSUE THREAD

**Issue by gcampion-cdisc** [cdisc-org/cdisc-rules-engine#228]
Sample Request
[cg0006.json.txt](https://github.com/cdisc-org/cdisc-rules-engine/files/10169542/cg0006.json.txt)

Links to related JIRA Tickets
https://jira.cdisc.org/browse/CORERULES-4
https://jira.cdisc.org/browse/CORERULES-49
https://jira.cdisc.org/browse/CORERULES-48

**Rule Information**
- **Standard**: SDTMIG
- **Rule Description**: 
  - CG0006: --DY calculated as per the study day algorithm as a non-zero integer value
  - CG0222: --ENDY is properly calculated per study day algorithm
  - CG0220: --STDY is properly calculated per study day algorithm

**Describe the bug**
1. The rule is giving incorrect results. In many cases, NAN is returned for the `dy` operator even when dates are correct. In the attached test request, there should be no issues.
1. The `dy` operator is returning 0 when it cannot calculate a result. Instead, it should be returning null. (If it returns 0, this will cause the rule to not flag data issues when the data has 0 instead of empty/null.)

Refer to previous related issue:
https://github.com/cdisc-org/cdisc-rules-engine/issues/152

**Comment by nhaydel** [comment]
@gcampion-cdisc the provided rule is written incorrectly. Here is it corrected: 
Notes:
1. Providing DM as the domain for the operation means that all comparisons will be done on the DM domain. Removing domain means that the calculation will be performed on the domain currently being evaluated.
2. I believe the goal was to calculate the difference between the --DTC value of the current domain and RFSTDTC in the DM domain. If that is the case then the "name" value in the operation needs to be "--DTC" with no domain provided
[dy_rule.json.txt](https://github.com/cdisc-org/cdisc-rules-engine/files/10344913/dy_rule.json.txt)
