### ISSUE TITLE
Rule blocked: CORERULES-777

### ISSUE THREAD

**Issue by eljanssens** [cdisc-org/cdisc-rules-engine#229]
Links to related JIRA Tickets
https://jira.cdisc.org/browse/CORERULES-777

Attachments
[CG0009_negative2-result.txt](https://github.com/cdisc-org/cdisc-rules-engine/files/10178080/CG0009_negative2-result.txt)
[CG0009_negative2-request.txt](https://github.com/cdisc-org/cdisc-rules-engine/files/10178082/CG0009_negative2-request.txt)

Rule Information
- SDTMIG 3.2, 3.3, 3.4
- CG0009
- Rule Description: Raise an error when EPOCH is not in TA.EPOCH

Describe the bug
Rule execution error: "error":"An unknown exception has occurred"
"message":"argument of type 'float' is not iterable"

Expected behavior
Error should not occur and output should be available for LB and EX dataset (like for AE)

**Comment by nhaydel** [comment]
Can you include the test data file used @eljanssens

**Comment by eljanssens** [comment]
Test data is available in the 'request.txt' attachment. But i've attached the excel sheet now as well
[unit-test-coreid-CG0009-negative.xlsx](https://github.com/cdisc-org/cdisc-rules-engine/files/10238741/unit-test-coreid-CG0009-negative.xlsx)

**Comment by nhaydel** [comment]
> Test data is available in the 'request.txt' attachment. But i've attached the excel sheet now as well
> 
> [unit-test-coreid-CG0009-negative.xlsx](https://github.com/cdisc-org/cdisc-rules-engine/files/10238741/unit-test-coreid-CG0009-negative.xlsx)
> 
> 

In the future it is better to either supply the request json as a .json file or the excel spreadsheet with test data since these are easier to parse than a text file.

**Comment by eljanssens** [comment]
Ok understood and will do so but please note that the guidelines for creating a CORE issue in gihub states: - Attach a .txt file with the JSON containing the full request. This can be copied from the Rule Editor under Test->Results->Request.

**Comment by nhaydel** [comment]
> Ok understood and will do so but please note that the guidelines for creating a CORE issue in gihub states: - Attach a .txt file with the JSON containing the full request. This can be copied from the Rule Editor under Test->Results->Request.
> 
> 

A text file is normally fine, the issue with the ones provided is they include more than just the json containing the full request. Things like "4 items" etc. are not valid json and make the request body difficult to parse using normal methods
