### ISSUE TITLE
Variable Metadata Needs to Include variable_format

### ISSUE THREAD

**Issue by nhaydel** [cdisc-org/cdisc-rules-engine#235]
The generated variable_metadata needs to include a variable_format column. This should be parsed from the xpt metadata

**Comment by nhaydel** [comment]
I will take this chance to extract the dataset builders into their own class

**Comment by nhaydel** [comment]
@nickdedonder how do we want to handle missing variable_format in xpt files. For example the files in the metadata submission guide do not include a variable format.

**Comment by nickdedonder** [comment]
@nhaydel missing formats will remain missing. A character variable will not have a format attached but a numeric might have one. I will look for some data
