### ISSUE TITLE
list-rules command returning duplicate rules

### ISSUE THREAD

**Issue by jamesformedix** [cdisc-org/cdisc-rules-engine#249]
Not really a bug that prevents the engine from working but thought it was worth recording. 

I've noticed certain rules returned in the JSON output of list-rules are returned more than once. For instance when I run `core.exe list-rules` on v0.5.4, CDISC.SDTMIG.CG0340 shows up twice in the output with what looks like identical JSON object values:
`{'core_id': 'CDISC.SDTMIG.CG0340', 'author': 'CDISC', 'reference': [{'Origin': 'SDTM and SDTMIG Conformance Rules', 'Rule_Identifier': {'Id': 'CG0340', 'Version': '1'}, 'Version': '2.0'}], 'sensitivity': 'Record', 'severity': 'error', 'description': 'Raise an error when --SCAT = --BODSYS.', 'authority': {'Organization': 'CDISC'}, 'standards': [{'Name': 'SDTMIG', 'Version': '3.4'}, {'Name': 'SDTMIG', 'Version': '3.3'}, {'Name': 'SDTMIG', 'Version': '3.2'}], 'classes': {'Include': ['Events']}, 'domains': {'Include': ['All']}, 'rule_type': 'Uniqueness', 'conditions': {'all': [{'name': 'get_dataset', 'operator': 'equal_to', 'value': {'target': '--SCAT', 'comparator': '--BODSYS'}}]}, 'actions': [{'name': 'generate_dataset_error_objects', 'params': {'message': '--SCAT is equal to --BODSYS.'}}], 'output_variables': ['--TERM', '--SCAT', '--BODSYS']}`

And again:
`{'core_id': 'CDISC.SDTMIG.CG0340', 'author': 'CDISC', 'reference': [{'Origin': 'SDTM and SDTMIG Conformance Rules', 'Rule_Identifier': {'Id': 'CG0340', 'Version': '1'}, 'Version': '2.0'}], 'sensitivity': 'Record', 'severity': 'error', 'description': 'Raise an error when --SCAT = --BODSYS.', 'authority': {'Organization': 'CDISC'}, 'standards': [{'Name': 'SDTMIG', 'Version': '3.4'}, {'Name': 'SDTMIG', 'Version': '3.3'}, {'Name': 'SDTMIG', 'Version': '3.2'}], 'classes': {'Include': ['Events']}, 'domains': {'Include': ['All']}, 'rule_type': 'Uniqueness', 'conditions': {'all': [{'name': 'get_dataset', 'operator': 'equal_to', 'value': {'target': '--SCAT', 'comparator': '--BODSYS'}}]}, 'actions': [{'name': 'generate_dataset_error_objects', 'params': {'message': '--SCAT is equal to --BODSYS.'}}], 'output_variables': ['--TERM', '--SCAT', '--BODSYS']}`

Another one being CDISC.SDTMIG.CG0338:
`{'core_id': 'CDISC.SDTMIG.CG0338', 'author': 'CDISC', 'reference': [{'Origin': 'SDTM and SDTMIG Conformance Rules', 'Rule_Identifier': {'Id': 'CG0338', 'Version': '1'}, 'Version': '2.0'}], 'sensitivity': 'Record', 'severity': 'error', 'description': 'Raise an error when --SCAT = --DECOD.', 'authority': {'Organization': 'CDISC'}, 'standards': [{'Name': 'SDTMIG', 'Version': '3.4'}, {'Name': 'SDTMIG', 'Version': '3.3'}, {'Name': 'SDTMIG', 'Version': '3.2'}], 'classes': {'Include': ['Events']}, 'domains': {'Include': ['All']}, 'rule_type': 'Uniqueness', 'conditions': {'all': [{'name': 'get_dataset', 'operator': 'equal_to_case_insensitive', 'value': {'target': '--SCAT', 'comparator': '--DECOD'}}]}, 'actions': [{'name': 'generate_dataset_error_objects', 'params': {'message': '--SCAT is equal to --DECOD.'}}], 'output_variables': ['--DECOD', '--SCAT']}`

And it appears in the JSON output again:
`{'core_id': 'CDISC.SDTMIG.CG0338', 'author': 'CDISC', 'reference': [{'Origin': 'SDTM and SDTMIG Conformance Rules', 'Rule_Identifier': {'Id': 'CG0338', 'Version': '1'}, 'Version': '2.0'}], 'sensitivity': 'Record', 'severity': 'error', 'description': 'Raise an error when --SCAT = --DECOD.', 'authority': {'Organization': 'CDISC'}, 'standards': [{'Name': 'SDTMIG', 'Version': '3.4'}, {'Name': 'SDTMIG', 'Version': '3.3'}, {'Name': 'SDTMIG', 'Version': '3.2'}], 'classes': {'Include': ['Events']}, 'domains': {'Include': ['All']}, 'rule_type': 'Uniqueness', 'conditions': {'all': [{'name': 'get_dataset', 'operator': 'equal_to_case_insensitive', 'value': {'target': '--SCAT', 'comparator': '--DECOD'}}]}, 'actions': [{'name': 'generate_dataset_error_objects', 'params': {'message': '--SCAT is equal to --DECOD.'}}], 'output_variables': ['--DECOD', '--SCAT']}`

**Comment by nhaydel** [comment]
good catch. This can be addressed with the updates to the schema, since the rule catalog will have to be updated then anyways. It should go out in the next release on Feb 6th

**Comment by nhaydel** [comment]
@jamesformedix this is caused by listing all rules. Because some rules exist for multiple standards, they exist in the set of rules for each standard. When listing rules you will see duplicates for rules that exist across standards. You can list rules for a specific standard using the -s and -v flag when listing rules. Is this acceptable?

**Comment by jamesformedix** [comment]
Hi Nic, you're right I've updated the application to use the various new rule sets available so now the rules are displaying uniquely as expected. Thanks
