### ISSUE TITLE
As VALIDATOR, I want to cross-check my study data against the study define.xml for missing variables so that I can stay compliant with SD0054 & SD0060

### ISSUE THREAD

**Issue by chowsanthony** [cdisc-org/cdisc-rules-engine#254]
1. SD0054 is the inverse of SD0060.
2. This check applies to SEND, SDTM, and ADaM data.
3. This check is IG-version-agnostic.

SD0054 in FDA VR v1.6:
- Rule message: Variable in define.xml is not present in the dataset
- Rule description: Variables listed in the data definition document (define.xml) should be included in the dataset.

SD0060 in FDA VR v1.6:
- Rule message: Variable in dataset is not present in define.xml
- Rule description: Variables included in the dataset must be described in the data definition document (define.xml).

**Comment by nickdedonder** [comment]
Not working on FDA validator issues at the moment
