### ISSUE TITLE
As VALIDATOR, I want to cross-check my study data against the study define.xml for null values in variables that are mandatory so that I can stay compliant with SD1229

### ISSUE THREAD

**Issue by chowsanthony** [cdisc-org/cdisc-rules-engine#256]
1. This check applies to SEND, SDTM, and ADaM data.
2. This check is IG-version-agnostic.
3. This check applies to both dataset definitions (ItemRef within ItemGroupDef) and value list definitions (ItemRef within def:ValueListDef)

SD1229 in FDA VR v1.6:
- Rule message: Variable value is null when value-level condition occurs
- Rule description: Variable value must be populated when value level attribute Mandatory='Yes' as specified in define.xml file.

**Comment by RamilCDISC** [comment]
During validation i made the VSORRESU variable order number 1 value null in dataset. The define file defines it as mandatory. After running the rule I observed that the null value was not caught by the engine, which fails the Acceptance Criteria. I have attached the generated report and rule, dataset and define file, to reproduce the issue.

<img width="1432" alt="Screen Shot 2023-07-28 at 4 17 12 PM" src="https://github.com/cdisc-org/cdisc-rules-engine/assets/113539111/2c58531e-0899-4d1c-ba32-5cb34965953a">

[test file.zip](https://github.com/cdisc-org/cdisc-rules-engine/files/12198529/test.file.zip)
[CORE-Report-2023-07-28T16-00-42.xlsx](https://github.com/cdisc-org/cdisc-rules-engine/files/12198528/CORE-Report-2023-07-28T16-00-42.xlsx)
