### ISSUE TITLE
As VALIDATOR, I want to cross-check my study data against the study define.xml for lack of comments or not indicating no data for expected variables that are always null so that I meet the business rule stated in the Define-XML specifications

### ISSUE THREAD

**Issue by chowsanthony** [cdisc-org/cdisc-rules-engine#257]
1. This check applies to SEND and SDTM data. ADaM does not have Core = Expected.
2. This check needs CDISC Library for the Core metadata.
3. This check is IG-version-agnostic.
4. This check is an extension to SD1149.

From the Define-XML v2.1 specifications:
- Used to indicate that an ItemRef that represent a dataset’s variable has no data. Note that variables refer to both standard and non-standard/ supplemental qualifiers variables (/ODM/Study/MetaDataVersion/ItemGroupDef/ItemRef or /ODM/Study/MetdataVersion/def:ValueListDef/ItemRef).
- Business Rule: A comment must be included to explain why no data is present for dataset’s variables that were planned for use in the study.

**Comment by nickdedonder** [comment]
Create "define_variable_has_comment"
