### ISSUE TITLE
As VALIDATOR, I want to cross-check my study data against the study define.xml for mismatching dataset variable labels so that I can stay compliant with SD1324

### ISSUE THREAD

**Issue by chowsanthony** [cdisc-org/cdisc-rules-engine#258]
1. This check applies to SEND, SDTM, and ADaM data.
2. This check is IG-version-agnostic.
3. This check is case sensitive.

SD1324 in FDA VR v1.6:
- Rule message: Define.xml/dataset variable label mismatch
- Rule description: Variable Label in define.xml must match variable Label in dataset.

**Comment by nickdedonder** [comment]
Should be covered by: https://github.com/cdisc-org/cdisc-rules-engine/blob/main/cdisc_rules_engine/dataset_builders/variables_metadata_with_define_dataset_builder.py
Ruletype is Variable Metadata Check against Define XML
Check is define_variable_label (name property)
Operator is not_equal_to
Value is variable_label
