### ISSUE TITLE
As VALIDATOR, I want to cross-check my study data against both the study define.xml and SENDIG for mismatching dataset variable labels so that I can stay compliant with SEND 6.

### ISSUE THREAD

**Issue by chowsanthony** [cdisc-org/cdisc-rules-engine#259]
1. This check only applies to SEND.
2. This check needs CDISC Library.
3. This check is IG-version-agnostic.
4. This check is case sensitive.

SEND 6 in v4.0:
- Rule: Metadata in Define-XML document should match both the SENDIG label and the label in the .xpt datasets.
- Rule explanation: Metadata in Define-XML document should match both the SENDIG label and the label in the .xpt datasets.

**Comment by nickdedonder** [comment]
The rules has been written and working. The rule has been split into 2 rules.
