### ISSUE TITLE
list-rules command returns empty string for "excecutability" for all rule sets

### ISSUE THREAD

**Issue by jamesformedix** [cdisc-org/cdisc-rules-engine#270]
I've just switched to the newest version of the CORE engine v0.5.5 which supports the new rule schema detailed here https://github.com/cdisc-org/cdisc-rules-engine/issues/224.
Whenever I call the list-rules command on any standard or version however, all the "executability" values return as empty strings. I have tried this with both sdtmig as well as sendig and received the same results.

**Comment by nhaydel** [comment]
@jamesformedix When converting to the new schema, executability  was not added to the rules by default so existing rules do not have executability yet

**Comment by jamesformedix** [comment]
Understood thanks for clarifying
