### ISSUE TITLE
As VALIDATOR, I want to cross-check my study data against the study define.xml for invalid units for normalized test parameters such as PK so that I can stay compliant with CG0556, CG0557, CG0559, CG0560

### ISSUE THREAD

**Issue by chowsanthony** [cdisc-org/cdisc-rules-engine#278]
Given an SDTM Findings domain in scope, and when test parameters matching certain nomenclature that indicates a normalization scheme, it is expected compatible units of measurement be used for the corresponding test results. Use cases are as follows.

**Assumptions**
- Variable PPTESTCD is populated using the CDISC CT codelist PKPARMCD (C85839).
- Variable PPTEST is populated using the CDISC CT codelist PKPARM (C85493).
- Values in PPORRESU and PPSTRESU are case-sensitive. E.g., "KG" is not valid symbol for kilogram.

**Case 1: Test parameters normalized by weight**
When:
- Domain: PP
- and PPTESTCD nomenclature: ends with W, except when it ends with DW (dose adjusted by body weight)

Check 1:
- Study define: variable PPORRESU does not use any of these CDISC CT codelists: PKUWG (C128684) or PKUWKG (C128683) or PKUNIT (C85494)
- and (study data: PPORRESU is not one of the values in the CDISC CT codelists and package date specified in the study define.
  - or study data: PPORRESU **does not end with** `/g` from PKUWG (C128684); or, does not end with `/kg` from PKUWKG (C128683); or does not end with `/g` or `/kg` from PKUNIT (C85494))

Check 2:
- Study define: variable PPSTRESU does not use any of these CDISC CT codelists: PKUWG (C128684) or PKUWKG (C128683) or PKUNIT (C85494)
- and (study data: PPSTRESU is not one of the values in the CDISC CT codelists and package date specified in the study define.
  - or data: PPSTRESU **does not end with** `/g` from PKUWG (C128684); or, does not end with `/kg` from PKUWKG (C128683); or, does not end with `/g` or `/kg` from PKUNIT (C85494))

**Case 2: Test parameters normalized by dose or weight-adjusted dose**
When:
- Domain: PP
- and PPTESTCD nomenclature: ends with D or ends with DW

Check 1:
- Study define: variable PPORRESU does not use any of these CDISC CT codelists: PKUDMG (C128685) or PKUDUG (C128686) or PKUNIT (C85494)
- and (study data: PPORRESU is not one of the values in the CDISC CT codelists and package date specified in the study define.
  - or study data: PPORRESU **does not contain** `/mg` from PKUDMG (C128685); or, does not contain `/ug` from PKUDUG (C128686); or, does not contain `/mg` or `/ug` from PKUNIT (C85494))

Check 2:
- Study define: variable PPSTRESU does not use any of these CDISC CT codelists: PKUDMG (C128685) or PKUDUG (C128686)
- and (study data: PPSTRESU is not one of the values in the CDISC CT codelists and package date specified in the study define.
  - or study data: PPSTRESU **does not contain** `/mg` from PKUDMG (C128685); or, does not contain `/ug` from PKUDUG (C128686); or, does not contain `/mg` or `/ug` from PKUNIT (C85494))

**Comment by chowsanthony** [comment]
I am investigating these other normalization schemes through NCI EVS:

Normalized by weight
PPTESTCD ends with W
PPORRESU/PPSTRESU should end with /g from PKUWG (C128684); or end with /kg from PKUWKG (C128683)

Normalized by dose
PPTESTCD ends with D
PPORRESU/PPSTRESU should contain with /mg from PKUDMG (C128685); or end with /ug from PKUDUG (C128686)

Normalized by dose & weight (weight-adjusted dose)
PPTESTCD ends with DW
PPORRESU/PPSTRESU should ???

Normalized by surface area (SA)
PPTESTCD ends with S
PPORRESU/PPSTRESU should contain m2 or cm2 from PKUNIT (C85494)

Normalized by BMI
PPTESTCD ends with B
PPORRESU/PPSTRESU should contains kg/m2 or mg/cm2 from PKUNIT (C85494)

**Comment by nhaydel** [comment]
@chowsanthony 

It seems like the rule will involve some variation of these 4 checks:

Raise an error if:

PPTESTCD ends in W but not DW and
The specified codelist(s) for PPSTRESU from the define are not contained by [C128684, C128683, C85494] and (PPSTRESU ends with /g or PPSTRESU ends with /kg)

If so we would just need the specified codelist for PPSTRESU from the define . Am I misunderstanding something?

**Comment by RamilCDISC** [comment]
The validation process is complete. The engine successfully checks the study data against the define xml for the scenarios mentioned in the Acceptance criteria. One of the reports generated for this scenario is attached below. It had 3 errors which were detected successfully. 

<img width="1205" alt="278" src="https://github.com/cdisc-org/cdisc-rules-engine/assets/113539111/e770da89-17eb-41db-bf6d-44cf7b9b53c8">

[CORE-Report-2023-06-14T15-40-47.xlsx](https://github.com/cdisc-org/cdisc-rules-engine/files/11750429/CORE-Report-2023-06-14T15-40-47.xlsx)
