### ISSUE TITLE
Null Executability causes the engine to crash

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/cdisc-rules-engine#293]
To reproduce:
1. From rule editor, select a rule
2. Ensure a property of "Executability" exists and the value for the property is empty
3. Load any test data to submit to the Rule engine

This will generate a json document with null Executability.
The TestRule endpoint returns a 500.

AC
The engine or endpoint should either handle the case of null Executability or return an error message stating the issue.

**Comment by nhaydel** [comment]
Does this happen when any field is present but empty or just executability?

**Comment by gerrycampion** [comment]
> Does this happen when any field is present but empty or just executability?

I tested a few other fields and only found the issue with executability
