### ISSUE TITLE
PDF files in folder with XPT files cause validator to crash

### ISSUE THREAD

**Issue by JozefAerts** [cdisc-org/cdisc-rules-engine#297]
Usually, in a "submission-ready" folder with SDTM files, one also has the define.xml, the stylesheet (*.xsl), and one or more PDF files.
Presence of a PDF and/or stylesheet currently causes the validator to crash.
The current workaround for us is to, when the validator is called, to first copy the XPT files to another directory (together with or without the define.xml), omitting the stylesheet and the PDF files.
Maybe the validator should work so that PDF and stylesheet files are just skipped,
and/or that only XPT files, XML files (for define.xml, but also in future for Dataset-XML files) and JSON files (for Dataset-JSON) are treated, and any others are automatically skipped.

**Comment by nhaydel** [comment]
This is a known issue: https://github.com/cdisc-org/cdisc-rules-engine/issues/196

**Comment by JozefAerts** [comment]
Thanks Nic!
I was looking for the word "PDF" in the list of issues, but did not find a hit.
So I submitted the issue, although I had a vague remembrence that something very similar has been reported already.
My apologies for this!

P.S. I am now at a stage that we are starting working on incorporating CORE validation into one of our commercial products! :-) :-) ;-). Maybe we can release on occasion of the European Interchange ...
