### ISSUE TITLE
Rule blocked: CORERULES-11 - merge parents with supps

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/cdisc-rules-engine#345]
**Links to related JIRA Tickets**
- https://jira.cdisc.org/browse/CORERULES-11

**Rule Information**
- **Standard**: SDTM
- **Rule ID**: CG0019
- **Rule Description**: Each record is unique per sponsor defined key variables as documented in the define.xml

**Describe the problem**
This is 1/3 of the solution to writing CG0019. Concatenate and Merge domains.  This should handle the cases for
- Split domains
- domains with SUPPs.

**Describe the solution**
For every domain:
1. all datasets belonging to the (split) domain should be concatenated
2. all supp datasets belonging to the domain should be merged in the following way:
   - The `RDOMAIN` of supp matches the `DOMAIN` of the parent
   - The merge keys will be, for the following variables that exist: `STUDYID`, `USUBJID`, `APID`, `POOLID`, `SPDEVID`, and `parent.[supp.IDVAR]=supp.IDVARVAL`
   - The newly created column should have `name=supp.QNAM`, `label=supp.QLABEL`, and `value=supp.QVAL`
   - If a single supp record matches multiple parent records, the corresponding supp values should appear on each matching parent row
   - If multiple supp records with the same `supp.QNAM` match a single parent record, this should cause an error
   - If the shape of the parent is `(R, C)` and there are `Q` distinct `supp.QNAMS`, the shape of the output dataset should be `(R, C+Q)`

**Comment by gerrycampion** [comment]
This might already work, but may be missing functionality. We will need to test `Merge Datasets` to see if it works as expected for this.

**Comment by nickdedonder** [comment]
@RamilCDISC test data can be found here: https://cdisc.sharepoint.com/:f:/r/sites/CORERules/Shared%20Documents/unitTesting/SDTMIG/[CG0019](https://cdisc.sharepoint.com/:f:/r/sites/CORERules/Shared%20Documents/unitTesting/SDTMIG/CG0019?csf=1&web=1&e=GYQC4E)?csf=1&web=1&e=GYQC4E

**Comment by SFJohnson24** [comment]
@RamilCDISC because the linked PR is only 1/3 of the solution of the issue descriped, I assume the expectation is that the test data will not run properly yet?

**Comment by RamilCDISC** [comment]
@SFJohnson24 I have updated my branch and merged all new commits of main into it. You can run a test using the following dataset and rule file.  I obtained the json dataset by uploading the excel file from sharepoint to the editor and then downloaded the artifacts. Upon running of test you will see successful execution of rule in the generated report rules tab.

You may see error printed in the terminal, they are because 2 datasets are missing some column....The rule successfully executes.

[Rule (8).zip](https://github.com/cdisc-org/cdisc-rules-engine/files/15030711/Rule.8.zip)

**Comment by SFJohnson24** [comment]
I discussed with @gerrycampion and @RamilCDISC the QA for this ticket and the need to for a unit test to confirm the merge functionality is being performed properly by the new code.

**Comment by SFJohnson24** [comment]
Marcelina is assigning this to make data but testing cannot occur until ticket is resolved.
