### ISSUE TITLE
Sponsor Specific Rules

### ISSUE THREAD

**Issue by dostiep** [cdisc-org/cdisc-rules-engine#392]
Hi,

Would it be possible to add an example in the README file on how to handle sponsor specific rules. I see there's an option "-r" for the "validate" but no details are mentionned for this option. 

Would it be possible to provide an example of a sponsor specific file (format, contents, etc.)?

I've tried multiple options but never been able to have it working.

Running this command generates the following issue:
core.py validate -s sdtmig -v 3-4 -d Examples/sdtm -dv 2.0 -r Examples/rules.json

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "C:\Python_3.10.2\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\U062293\core\cdisc-rules-engine-main\scripts\run_validation.py", line 50, in validate_single_rule
    rule["conditions"]
TypeError: 'NoneType' object is not subscriptable
"""

I've tried with my rules.json file in the same format as the CDISC rules and also in the same format as the one generated from the conformance-rules-editor without success.

I just need to know if this option is working and how the JSON file should look like.

Thanks

**Comment by nhaydel** [comment]
The engine does not currently support sponsor defined rules, but that is something we hope to implement soon

**Comment by dostiep** [comment]
Thank you for coming back so quickly. Do we know at least the file format sponsor rules will need to be (JSON, YAML)?

Just so we can start working on our rules and be able to start testing them as soon as the engine permits.
