### ISSUE TITLE
CLI Rule tester (test) should accept rule yaml

### ISSUE THREAD

**Issue by gerrycampion** [cdisc-org/cdisc-rules-engine#430]
Currently, the cli rule tester only accepts a json rule. 

AC
The cli rule tester (test) should accept:
- raw yaml rules as they would be entered in the rule editor

It can use this function to convert underscores:
- https://github.com/cdisc-org/rule-transformations/blob/942604496898d06f16c39afd04a67f03541e2ff3/transformer/transformer.py#L124

**Comment by nickdedonder** [comment]
Yaml rules can be run with the local rules functionality
