### ISSUE TITLE
Rule blocked: CORERULES-CG0232, CG0233, CG0234, CG0235

### ISSUE THREAD

**Issue by TCasteris** [cdisc-org/cdisc-rules-engine#527]
- Attach a .txt file with the JSON containing the full request. This can be copied from the Rule Editor under Test->Results->Request.
- Replace the "###" in the issue title with the primary JIRA ticket number for the rule. 
- 
- Fill in the following information

**Links to related JIRA Tickets**
CG0232: https://jira.cdisc.org/browse/CORERULES-273
CG0233: https://jira.cdisc.org/browse/CORERULES-274
CG0234: https://jira.cdisc.org/browse/CORERULES-275
CG0235: https://jira.cdisc.org/browse/CORERULES-276

**Rule Information**
- **Standard**:
- **Rule ID**:
- **Rule Description**:

**Describe the bug**
date_equal_to operator is not working correctly when one of the dates is not present on the dataset

**Error returned from Rule Engine**
"Unknown string format: CMDTC"

**Expected behavior**
Would expect the CM dataset to be skipped if CMDTC is not present

**Comment by nhaydel** [comment]
If it is a common practice to skip a rule when an operator requires a variable that is not present, I believe we should handle that in a single issue with an update that applies to all operators

**Comment by SFJohnson24** [comment]
@nickdedonder made edits to this rules and it has been moved to QC.  The behavior noted above is expected.  Moving this ticket to closed.
