### ISSUE TITLE
Update dataset builders to operate on and return instances of a Dataset class

### ISSUE THREAD

**Issue by nhaydel** [cdisc-org/cdisc-rules-engine#549]
* Merge changes into datset abstraction branch
* All dataset builders return an instance of the DatasetInterface

**Comment by gerrycampion** [comment]
For reference, the dataset builders are here: https://github.com/cdisc-org/cdisc-rules-engine/tree/ISS-536-datasets-abstraction/cdisc_rules_engine/dataset_builders

**Comment by gerrycampion** [comment]
Completed by: https://github.com/cdisc-org/cdisc-rules-engine/pull/615
