### ISSUE TITLE
Update present_on_multiple_rows_within and not_present_on_multiple_rows_within operators to work with entities

### ISSUE THREAD

**Issue by ASL-rmarshall** [cdisc-org/cdisc-rules-engine#591]
These operators currently return a `'DataFrame' object has no attribute 'tolist'` error when used with a DDF/USDM entity.

**Comment by ASL-rmarshall** [comment]
The operators return the error when there's only a single group of values in the variable specified in `within` - this is true for both DDF/USDM entities and SDTM domains/datasets.  See #599

**Comment by nickdedonder** [comment]
Issue has been superseded by #599
