### ISSUE TITLE
Alignment output report format XLSX - JSON

### ISSUE THREAD

**Issue by rradel** [cdisc-org/cdisc-rules-engine#595]
There seems to be a difference between the output report provided in XLSX and JSON, where the XLSX report seems to have evolved, the JSON report has not. e.g. in the JSON output the datasets are not listed with their timestamp, the labels of the different tabs in XLSX are not the same as the tags used in JSON

**Comment by SFJohnson24** [comment]
Adding to this ticket
- adding dataset domain into the dataset details of the XLSX report
- updating the json report to be more informative as requested above, dataset names instead of just domains validated in JSON result

**Comment by mhungria** [comment]
I support this ticket.

**Comment by mhungria** [comment]
[Rule (7).zip](https://github.com/user-attachments/files/16336473/Rule.7.zip)

**Comment by mhungria** [comment]
@SFJohnson24 , as per our meeting today, I added the zip file with the incorrect result identifying "CMX" as the results for a dataset named "CMX" (taken from the dataset's domain name instead of the interpreted dataset name:
<img width="698" alt="image" src="https://github.com/user-attachments/assets/b9c7a1cc-a9fb-4dbf-a9a4-cbf367990154">

**Comment by SFJohnson24** [comment]
Note: when a validation occurs, the result JSON's keys are domains.  It would be useful to give both the domain that is validated but also the dataset name that is associated with that validation that has run.  Below is QS domain but there is no information regarding the dataset name that was skipped.
![image](https://github.com/user-attachments/assets/cacbbb3e-2997-488c-977b-44cab420f16b)

**Comment by mhungria** [comment]
See https://github.com/cdisc-org/cdisc-rules-engine/pull/771
