### ISSUE TITLE
RuleType Value Check against Define XML Variable: Domain for SUPP* datasets

### ISSUE THREAD

**Issue by mhungria** [cdisc-org/cdisc-rules-engine#638]
Need clarification on where the Domain value is retrieved from, for both the main dataset and SUPP datasets, in particular for RuleType Value Check against Define XML Variable or any rule types against Define-XML.
Note: it appears to be a **BUG.**

<img width="577" alt="image" src="https://github.com/cdisc-org/cdisc-rules-engine/assets/8083492/769f0d16-8b16-40b0-a384-7d06665e302c">

Here is the Define-XML snippet:
<img width="580" alt="image" src="https://github.com/cdisc-org/cdisc-rules-engine/assets/8083492/2e0d127e-7171-4927-bc52-7b9aa78afa0b">

**Comment by chowsanthony** [comment]
@mhungria Can you confirm you receiving the validation result even though suppec.xpt is in the data folder and it is defined in the study define file?

**Comment by mhungria** [comment]
@chowsanthony , this is a general question about the difference between a dataset name and its domain. Since I didn't keep the actual test conditions I used at the time for this question, I executed again with a different test conditions and I'm attaching here the corresponding Rule.4.zip file: 
[Rule (4).zip](https://github.com/cdisc-org/cdisc-rules-engine/files/15210014/Rule.4.zip).

**Comment by mhungria** [comment]
@SFJohnson24 , all: you may want to also look at https://github.com/cdisc-org/cdisc-rules-engine/issues/633
