### ISSUE TITLE
Rule blocked: CORERULES-### / CG-0321 - Results - Fail: 502 

### ISSUE THREAD

**Issue by mhungria** [cdisc-org/cdisc-rules-engine#695]
Request and results set on the zip file attached.
- 
[Rule (5).zip](https://github.com/cdisc-org/cdisc-rules-engine/files/15235547/Rule.5.zip)

**Links to related JIRA Tickets**

[CORERULES-272](https://jira.cdisc.org/browse/CORERULES-272)

**Describe the bug**
A clear and concise description of what the bug is: Results - Fail: 502 - ...

**Expected behavior**
An appropriate result not a system error.

**Comment by nhaydel** [comment]
@gerrycampion I am not able to reproduce this issue. Maybe it was resolved in another PR?

**Comment by mhungria** [comment]
@nhaydel , @gerrycampion : the 502 error appear to have been resolved. It would be nice to know what was causing the issue and how it got resolved.

In any case, issues related to [CORERULES-272](https://jira.cdisc.org/browse/CORERULES-272) still exist.

**Comment by nickdedonder** [comment]
Error no longer exists and we have no easy way to track down the cause.
