### ISSUE TITLE
With Joe Ben and IT, Sign up for the service where we can build the Azure container instance

### ISSUE THREAD

**Issue by drewcdisc** [cdisc-org/cdisc-rules-engine#765]

**Comment by SFJohnson24** [comment]
@joebenclark yes this is what I had in mind.  We may need to persist the report after the container spins down so we may also need Azure Files mounted to the container.  https://learn.microsoft.com/en-us/azure/container-instances/container-instances-volume-azure-files  I have not looked into whether we can get the report after the run before the container spins down, in which case this may not be necessary.

**Comment by SFJohnson24** [comment]
@joebenclark  I met with @gerrycampion yesterday and discussed the test suite.  We agreed on an architecture that would only need git actions so we may not need to provision any azure resources for this.  I will keep this ticket up in case we reach a block with git actions implementation but using only git actions would have the benefit of not just simplicity but also cost savings.

**Comment by gerrycampion** [comment]
We went with gh actions
