### ISSUE TITLE
Compose the docker file

### ISSUE THREAD

**Issue by drewcdisc** [cdisc-org/cdisc-rules-engine#766]

**Comment by SFJohnson24** [comment]
This ticket has been moved back to the product backlog after discussing the test suite architecture among the developers.  We believe we can perform the test suite purely in git actions without need for provisioning azure resources/a docker container.  We do still feel the docker implementation is an important tool for testing large datasets on containerized engine in a cloud environment and as a utility that our stakeholders will want to use.
