### ISSUE TITLE
GitHub action to build the container for each release

### ISSUE THREAD

**Issue by drewcdisc** [cdisc-org/cdisc-rules-engine#768]
Build an action that will pull the latest release and build the container for Docker hub.

**Comment by drewcdisc** [comment]
The config should allow the customer to config the docker installation so that the folders in their hosted environement can map to folders within the docker container. Current set of folders:
- Vendor's local rules folder
- Vendor's dataset folder
- Exported report(s) folder

**Comment by SFJohnson24** [comment]
I believe #796 would cover this.  Our image would grab the latest release of engine for the container so we would not need to update the image for each release.  I agree on the mapping logic for custom implementations for vendors
