### ISSUE TITLE
Test Suite: invalid_duration

### ISSUE THREAD

**Issue by SFJohnson24** [cdisc-org/cdisc-rules-engine#779]
the new operator invalid_duration does not have any rules for it yet.  When there is a rule created with it, it needs to be added to the test suite

**Comment by JozefAerts** [comment]
There is a rule SEND59.1 for this: "--EVLINT, --ELTM, --DUR must be in **ISO 8601 duration format**, including the additional format that allows the representation of  negative intervals of time."
I have a (negative) test file for this on Sharepoint at:
https://cdisc.sharepoint.com/sites/CORERules/Shared%20Documents/Forms/AllItems.aspx?id=%2Fsites%2FCORERules%2FShared%20Documents%2FunitTesting%2FSENDIG%2FSENDIG059%2Fnegative%2F01%2Fdata&viewid=ecd009a9%2Db73b%2D415b%2D9e41%2Df9d04a69edf4 
In the rule editor, we do have a YAML script for it, which uses regular expressions. Shall I change it to use "invalid_duration" function?

**Comment by SFJohnson24** [comment]
invalid_duration function has been merged so there is access to the operator if you want to try using it @JozefAerts.  I can always tweak the function if you have an issue with it.

**Comment by SFJohnson24** [comment]
this ticket has been migrated to the test rule repo: https://app.zenhub.com/workspaces/core-dx-63fe768d89cdf600116ba028/issues/gh/cdisc-org/core_test_suite/3
