### ISSUE TITLE
docker

### ISSUE THREAD

**Issue by SFJohnson24** [cdisc-org/cdisc-rules-engine#796]
create a more generalized dockerImage that stakeholders could use more seamlessly to run validations.
potential AC:
- 2 docker images hosted on dockerhub with one for a LR validation and one for a validation with CORE-IDs.  
- readme for implementation

**Comment by SFJohnson24** [comment]
see: #766

**Comment by SFJohnson24** [comment]
per Drew's other ticket: The config should allow the customer to config the docker installation so that the folders in their hosted environement can map to folders within the docker container. Current set of folders:

    Vendor's local rules folder
    Vendor's dataset folder
    Exported report(s) folder

**Comment by drewcdisc** [comment]
Additionally, this version would be a precursor to providing a certifiable version of CORE.  We are not there yet, but eventually we want for the datasets and rules to have specific versions that a specific version of the engine can be certified against. This external version of the docker file will enable that, in the future. This step is NOT part of this PBI, but we will need to include this later.

**Comment by SFJohnson24** [comment]
for this ticket: I discussed with Gerry and opted for a more broad implementation on dockerhub and laid out how to perform volume mounts with local file directories onto the container to run the CLI commands.  I believe giving our stakeholders a containerized engine without the constraints of an expected file system path where the docker commands are being run will be much more useful to stakeholders as they can customize for their implementation.
